version: "2"
linters:
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - containedctx
    - gocheckcompilerdirectives
    - gofmt
    - gofumpt
    - gosimple
    - govet
    - ineffassign
    - intrange
    - makezero
    - misspell
    - nilerr
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - unconvert
    - usetesting
    - wastedassign
    - whitespace
  disable:
    - errcheck
    - usestdlibvars
  settings:
    staticcheck:
      checks:
        - all
        - -SA1019 # omit Deprecated check
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
